class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Agrivyaan',
      'home': 'Home',
      'fields': 'Fields',
      'scans': 'Scans',
      'reports': 'Reports',
      'more': 'More',
      'my_farm': 'My Farm',
      'today': 'Today',
      'spraying_condition': 'Spraying Condition',
      'weather_spraying': 'Weather & Spraying',
      'farm_tools': 'Farm Tools',
      'crop_library': 'Crop Library',
      'pest_library': 'Pest Library',
      'disease_library': 'Disease Library',
      'ai_assistant': 'AI Farmer Assistant',
      'ai_assistant_sub': 'Voice & Multilingual Agronomist powered by Sarvam AI',
      'ask_anything': 'Ask any farming query or tap mic...',
      'listening': 'Listening... Speak now in your language',
      'speaking': 'Playing audio response...',
      'type_or_speak': 'Type question or tap mic to speak',
      'listen_audio': 'Listen Voice',
      'stop_audio': 'Stop Voice',
      'quick_questions': 'Quick Questions',
      'my_actions': 'My Actions',
      'profile': 'Profile',
      'settings': 'Settings',
      'add_field': 'Add Field',
      'request_scan': 'Request Drone Scan',
      'view_weather': 'View Weather',
      'tools': 'Tools',
      'ask_ai': 'Ask AI',
      'view_report': 'View Report',
      'health_score': 'Field Health',
      'soil_moisture': 'Soil Moisture',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'active_alerts': 'Active Alerts',
      'crop_stage': 'Crop Stage',
      'last_scan': 'Last Scan',
      'next_scan': 'Next Scan',
      'why': 'WHY?',
      'what_should_i_do': 'WHAT SHOULD I DO?',
      'record_action': 'Record Action',
      'view_zone': 'View Zone',
      'before_after': 'Before → Action → After',
      'early_warning': 'Early Warning',
      'offline_mode': 'Offline Mode (Data Cached)',
      'offline_sync': 'Sync Offline Data',
      'language': 'Language',
      'role': 'Current Role',
      'irrigation_calc': 'Irrigation Calculator',
      'fertilizer_calc': 'Fertilizer Calculator',
      'pesticide_calc': 'Pesticide Calculator',
      'seed_calc': 'Seed Calculator',
      'cost_calc': 'Farming Cost Calculator',
      'area_calc': 'Farm Area Calculator',
      'prompt_health': 'Why is my field health decreasing?',
      'prompt_weather': 'Is weather suitable for spraying today?',
      'prompt_zone': 'What is the moisture issue in Zone 2?',
      'prompt_blight': 'How to prevent leaf blight in my crops?',
    },
    'hi': {
      'app_title': 'एग्रीव्यान',
      'home': 'मुख्य पृष्ठ',
      'fields': 'खेत',
      'scans': 'स्कैन',
      'reports': 'रिपोर्ट',
      'more': 'अधिक',
      'my_farm': 'मेरा खेत',
      'today': 'आज का मौसम',
      'spraying_condition': 'छिड़काव की स्थिति',
      'weather_spraying': 'मौसम और छिड़काव',
      'farm_tools': 'कृषि उपकरण',
      'crop_library': 'फसल पुस्तकालय',
      'pest_library': 'कीट पुस्तकालय',
      'disease_library': 'रोग पुस्तकालय',
      'ai_assistant': 'एआई किसान सहायक',
      'ai_assistant_sub': 'सर्वम एआई द्वारा संचालित बहुभाषी आवाज कृषि विशेषज्ञ',
      'ask_anything': 'खेती से जुड़ा कोई भी सवाल पूछें या माइक दबाएं...',
      'listening': 'सुन रहा हूँ... अपनी भाषा में बोलें',
      'speaking': 'आवाज में उत्तर चला रहा हूँ...',
      'type_or_speak': 'प्रश्न लिखें या बोलने के लिए माइक दबाएं',
      'listen_audio': 'आवाज सुनें',
      'stop_audio': 'आवाज रोकें',
      'quick_questions': 'त्वरित प्रश्न',
      'my_actions': 'मेरे कार्य',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'add_field': 'नया खेत जोड़ें',
      'request_scan': 'ड्रोन स्कैन का अनुरोध करें',
      'view_weather': 'मौसम देखें',
      'tools': 'कैलकुलेटर',
      'ask_ai': 'एआई से पूछें',
      'view_report': 'रिपोर्ट देखें',
      'health_score': 'फसल स्वास्थ्य',
      'soil_moisture': 'मृदा नमी',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'active_alerts': 'सक्रिय अलर्ट',
      'crop_stage': 'फसल की अवस्था',
      'last_scan': 'पिछला स्कैन',
      'next_scan': 'अगला स्कैन',
      'why': 'क्यों?',
      'what_should_i_do': 'मुझे क्या करना चाहिए?',
      'record_action': 'कार्य दर्ज करें',
      'view_zone': 'ज़ोन देखें',
      'before_after': 'पहले → कार्य → बाद में',
      'early_warning': 'प्रारंभिक चेतावनी',
      'offline_mode': 'ऑफ़लाइन मोड (डेटा सहेजा गया)',
      'offline_sync': 'डेटा सिंक करें',
      'language': 'भाषा',
      'role': 'सक्रिय भूमिका',
      'irrigation_calc': 'सिंचाई कैलकुलेटर',
      'fertilizer_calc': 'उर्वरक कैलकुलेटर',
      'pesticide_calc': 'कीटनाशक कैलकुलेटर',
      'seed_calc': 'बीज कैलकुलेटर',
      'cost_calc': 'लागत कैलकुलेटर',
      'area_calc': 'क्षेत्रफल कैलकुलेटर',
      'prompt_health': 'मेरे खेत का स्वास्थ्य क्यों घट रहा है?',
      'prompt_weather': 'क्या आज छिड़काव के लिए मौसम सही है?',
      'prompt_zone': 'ज़ोन 2 में नमी की क्या समस्या है?',
      'prompt_blight': 'फसल में पत्ती झुलसा रोग से कैसे बचें?',
    },
    'mr': {
      'app_title': 'अॅग्रीव्यान',
      'home': 'मुख्यपृष्ठ',
      'fields': 'शेती',
      'scans': 'स्कॅन',
      'reports': 'अहवाल',
      'more': 'अधिक',
      'my_farm': 'माझी शेती',
      'today': 'आजचे हवामान',
      'spraying_condition': 'फवारणीची स्थिती',
      'weather_spraying': 'हवामान आणि फवारणी',
      'farm_tools': 'शेती साधने',
      'crop_library': 'पीक माहिती',
      'pest_library': 'कीड माहिती',
      'disease_library': 'रोग माहिती',
      'ai_assistant': 'कृषी AI मदतनीस',
      'ai_assistant_sub': 'सर्वम AI द्वारे संचलित बहुभाषिक आवाज कृषी तज्ज्ञ',
      'ask_anything': 'शेतीविषयक कोणताही प्रश्न विचारा किंवा माईक दाबा...',
      'listening': 'ऐकत आहे... तुमच्या भाषेत बोला',
      'speaking': 'आवाज उत्तर चालू आहे...',
      'type_or_speak': 'प्रश्न लिहा किंवा बोलण्यासाठी माईक दाबा',
      'listen_audio': 'आवाज ऐका',
      'stop_audio': 'आवाज थांबवा',
      'quick_questions': 'झटपट प्रश्न',
      'my_actions': 'माझ्या कृती',
      'profile': 'प्रोफाईल',
      'settings': 'सेटिंग्ज',
      'add_field': 'नवीन शेत जोडा',
      'request_scan': 'ड्रोन स्कॅन मागणी करा',
      'view_weather': 'हवामान पहा',
      'tools': 'कॅल्क्युलेटर',
      'ask_ai': 'AI ला विचारा',
      'view_report': 'अहवाल पहा',
      'health_score': 'पीक आरोग्य',
      'soil_moisture': 'मातीतील ओलावा',
      'temperature': 'तापमान',
      'humidity': 'हवेतील दमटपणा',
      'active_alerts': 'सक्रिय इशारे',
      'crop_stage': 'पिकाची अवस्था',
      'last_scan': 'शेवटचा स्कॅन',
      'next_scan': 'पुढील स्कॅन',
      'why': 'का?',
      'what_should_i_do': 'मी काय केले पाहिजे?',
      'record_action': 'कृतीची नोंद करा',
      'view_zone': 'झोन पहा',
      'before_after': 'पूर्वी → कृती → नंतर',
      'early_warning': 'पूर्व इशारा',
      'offline_mode': 'ऑफलाईन मोड (माहिती सुरक्षित)',
      'offline_sync': 'ऑफलाईन डेटा सिंक करा',
      'language': 'भाषा',
      'role': 'सक्रिय भूमिका',
      'irrigation_calc': 'सिंचन कॅल्क्युलेटर',
      'fertilizer_calc': 'खत कॅल्क्युलेटर',
      'pesticide_calc': 'कीटकनाशक कॅल्क्युलेटर',
      'seed_calc': 'बियाणे कॅल्क्युलेटर',
      'cost_calc': 'खर्च कॅल्क्युलेटर',
      'area_calc': 'क्षेत्रफळ कॅल्क्युलेटर',
      'prompt_health': 'माझ्या शेताचे आरोग्य का कमी होत आहे?',
      'prompt_weather': 'आज फवारणीसाठी हवामान योग्य आहे का?',
      'prompt_zone': 'झोन २ मध्ये ओलाव्याची काय समस्या आहे?',
      'prompt_blight': 'पिकातील करपा रोगापासून बचाव कसा करावा?',
    },
    'gu': {
      'app_title': 'એગ્રીવ્યાન',
      'home': 'મુખ્ય પૃષ્ઠ',
      'fields': 'ખેતર',
      'scans': 'સ્કેન',
      'reports': 'રિપોર્ટ',
      'more': 'વધુ',
      'my_farm': 'મારું ખેતર',
      'today': 'આજનું હવામાન',
      'spraying_condition': 'છાંટવાની સ્થિતિ',
      'weather_spraying': 'હવામાન અને છંટકાવ',
      'farm_tools': 'ખેતીના સાધનો',
      'crop_library': 'પાક માહિતી',
      'pest_library': 'જીવાત માહિતી',
      'disease_library': 'રોગ માહિતી',
      'ai_assistant': 'એઆઈ ખેડૂત સહાયક',
      'ai_assistant_sub': 'સર્વમ AI દ્વારા સંચાલિત બહુભાષી કૃષિ નિષ્ણાત',
      'ask_anything': 'ખેતી સંબંધિત કોઈપણ પ્રશ્ન પૂછો અથવા માઇક દબાવો...',
      'listening': 'સાંભળી રહ્યા છીએ... તમારી ભાષામાં બોલો',
      'speaking': 'અવાજ ઉત્તર ચાલુ છે...',
      'type_or_speak': 'પ્રશ્ન લખો અથવા બોલવા માટે માઇક દબાવો',
      'listen_audio': 'અવાજ સાંભળો',
      'stop_audio': 'અવાજ રોકો',
      'quick_questions': 'ઝડપી પ્રશ્નો',
      'my_actions': 'મારા કાર્યો',
      'profile': 'પ્રોફાઇલ',
      'settings': 'સેટિંગ્સ',
      'add_field': 'નવું ખેતર ઉમેરો',
      'request_scan': 'ડ્રોન સ્કેનની વિનંતી કરો',
      'view_weather': 'હવામાન જુઓ',
      'tools': 'કેલ્ક્યુલેટર',
      'ask_ai': 'AI ને પૂછો',
      'view_report': 'રિપોર્ટ જુઓ',
      'health_score': 'પાક સ્વાસ્થ્ય',
      'soil_moisture': 'જમીનનો ભેજ',
      'temperature': 'તાપમાન',
      'humidity': 'ભેજ',
      'active_alerts': 'સક્રિય અલર્ટ',
      'crop_stage': 'પાકની અવસ્થા',
      'last_scan': 'છેલ્લું સ્કેન',
      'next_scan': 'આગામી સ્કેન',
      'why': 'શા માટે?',
      'what_should_i_do': 'મારે શું કરવું જોઈએ?',
      'record_action': 'કાર્ય નોંધો',
      'view_zone': 'ઝોન જુઓ',
      'before_after': 'પહેલાં → કાર્ય → પછી',
      'early_warning': 'પ્રારંભિક ચેતવણી',
      'offline_mode': 'ઓફલાઇન મોડ',
      'offline_sync': 'ડેટા સિંક કરો',
      'language': 'ભાષા',
      'role': 'વર્તમાન ભૂમિકા',
      'irrigation_calc': 'સિંચાઈ કેલ્ક્યુલેટર',
      'fertilizer_calc': 'ખાતર કેલ્ક્યુલેટર',
      'pesticide_calc': 'જંતુનાશક કેલ્ક્યુલેટર',
      'seed_calc': 'બીજ કેલ્ક્યુલેટર',
      'cost_calc': 'ખર્ચ કેલ્ક્યુલેટર',
      'area_calc': 'ક્ષેત્રફળ કેલ્ક્યુલેટર',
      'prompt_health': 'મારા ખેતરનું સ્વાસ્થ્ય કેમ ઘટી રહ્યું છે?',
      'prompt_weather': 'શું આજે છંટકાવ માટે હવામાન અનુકૂળ છે?',
      'prompt_zone': 'ઝોન 2 માં ભેજની શું સમસ્યા છે?',
      'prompt_blight': 'પાકમાં સુકારાના રોગથી કેવી રીતે બચવું?',
    },
    'pa': {
      'app_title': 'ਐਗਰੀਵਿਆਨ',
      'home': 'ਮੁੱਖ ਪੰਨਾ',
      'fields': 'ਖੇਤ',
      'scans': 'ਸਕੈਨ',
      'reports': 'ਰਿਪੋਰਟਾਂ',
      'more': 'ਹੋਰ',
      'my_farm': 'ਮੇਰਾ ਖੇਤ',
      'today': 'ਅੱਜ ਦਾ ਮੌਸਮ',
      'spraying_condition': 'ਛਿੜਕਾਅ ਦੀ ਸਥਿਤੀ',
      'weather_spraying': 'ਮੌਸਮ ਅਤੇ ਛਿੜਕਾਅ',
      'farm_tools': 'ਖੇਤੀ ਸੰਦ',
      'crop_library': 'ਫਸਲ ਜਾਣਕਾਰੀ',
      'pest_library': 'ਕੀੜੇ ਜਾਣਕਾਰੀ',
      'disease_library': 'ਬਿਮਾਰੀ ਜਾਣਕਾਰੀ',
      'ai_assistant': 'ਏਆਈ ਕਿਸਾਨ ਸਹਾਇਕ',
      'ai_assistant_sub': 'ਸਰਵਮ AI ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਬਹੁ-ਭਾਸ਼ਾਈ ਖੇਤੀਬਾੜੀ ਮਾਹਰ',
      'ask_anything': 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਕੋਈ ਪ੍ਰਸ਼ਨ ਪੁੱਛੋ ਜਾਂ ਮਾਈਕ ਦਬਾਓ...',
      'listening': 'ਸੁਣ ਰਿਹਾ ਹੈ... ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ',
      'speaking': 'ਆਵਾਜ਼ ਉੱਤਰ ਚੱਲ ਰਿਹਾ ਹੈ...',
      'type_or_speak': 'ਪ੍ਰਸ਼ਨ ਲਿਖੋ ਜਾਂ ਬੋਲਣ ਲਈ ਮਾਈਕ ਦਬਾਓ',
      'listen_audio': 'ਆਵਾਜ਼ ਸੁਣੋ',
      'stop_audio': 'ਆਵਾਜ਼ ਰੋਕੋ',
      'quick_questions': 'ਤੇਜ਼ ਪ੍ਰਸ਼ਨ',
      'my_actions': 'ਮੇਰੇ ਕੰਮ',
      'profile': 'ਪ੍ਰੋਫਾਈਲ',
      'settings': 'ਸੈਟਿੰਗਾਂ',
      'add_field': 'ਨਵਾਂ ਖੇਤ ਜੋੜੋ',
      'request_scan': 'ਡਰੋਨ ਸਕੈਨ ਦੀ ਬੇਨਤੀ ਕਰੋ',
      'view_weather': 'ਮੌਸਮ ਵੇਖੋ',
      'tools': 'ਕੈਲਕੁਲੇਟਰ',
      'ask_ai': 'AI ਨੂੰ ਪੁੱਛੋ',
      'view_report': 'ਰਿਪੋਰਟ ਵੇਖੋ',
      'health_score': 'ਫਸਲ ਸਿਹਤ',
      'soil_moisture': 'ਮਿੱਟੀ ਦੀ ਨਮੀ',
      'temperature': 'ਤਾਪਮਾਨ',
      'humidity': 'ਨਮੀ',
      'active_alerts': 'ਐਕਟਿਵ ਅਲਰਟ',
      'crop_stage': 'ਫਸਲ ਦਾ ਪੜਾਅ',
      'last_scan': 'ਆਖਰੀ ਸਕੈਨ',
      'next_scan': 'ਅਗਲਾ ਸਕੈਨ',
      'why': 'ਕਿਉਂ?',
      'what_should_i_do': 'ਮੈਨੂੰ ਕੀ ਕਰਨਾ ਚਾਹੀਦਾ ਹੈ?',
      'record_action': 'ਕੰਮ ਦਰਜ ਕਰੋ',
      'view_zone': 'ਜ਼ੋਨ ਵੇਖੋ',
      'before_after': 'ਪਹਿਲਾਂ → ਕੰਮ → ਬਾਅਦ ਵਿੱਚ',
      'early_warning': 'ਸ਼ੁਰੂਆਤੀ ਚੇਤਾਵਨੀ',
      'offline_mode': 'ਆਫਲਾਈਨ ਮੋਡ',
      'offline_sync': 'ਡੇਟਾ ਸਿੰਕ ਕਰੋ',
      'language': 'ਭਾਸ਼ਾ',
      'role': 'ਮੌਜੂਦਾ ਭੂਮਿਕਾ',
      'irrigation_calc': 'ਸਿੰਚਾਈ ਕੈਲਕੁਲੇਟਰ',
      'fertilizer_calc': 'ਖਾਦ ਕੈਲਕੁਲੇਟਰ',
      'pesticide_calc': 'ਕੀਟਨਾਸ਼ਕ ਕੈਲਕੁਲੇਟਰ',
      'seed_calc': 'ਬੀਜ ਕੈਲਕੁਲੇਟਰ',
      'cost_calc': 'ਲਾਗਤ ਕੈਲਕੁਲੇਟਰ',
      'area_calc': 'ਖੇਤਰਫਲ ਕੈਲਕੁਲੇਟਰ',
      'prompt_health': 'ਮੇਰੇ ਖੇਤ ਦੀ ਸਿਹਤ ਕਿਉਂ ਘਟ ਰਹੀ ਹੈ?',
      'prompt_weather': 'ਕੀ ਅੱਜ ਛਿੜਕਾਅ ਲਈ ਮੌਸਮ ਠੀਕ ਹੈ?',
      'prompt_zone': 'ਜ਼ੋਨ 2 ਵਿੱਚ ਨਮੀ ਦੀ ਕੀ ਸਮੱਸਿਆ ਹੈ?',
      'prompt_blight': 'ਫਸਲ ਵਿੱਚ ਬਿਮਾਰੀ ਤੋਂ ਕਿਵੇਂ ਬਚੀਏ?',
    },
    'kn': {
      'app_title': 'ಅಗ್ರಿಮ್ಯಾನ್',
      'home': 'ಮುಖ್ಯ ಪುಟ',
      'fields': 'ಜಮೀನು',
      'scans': 'ಸ್ಕ್ಯಾನ್',
      'reports': 'ವರದಿಗಳು',
      'more': 'ಇನ್ನಷ್ಟು',
      'my_farm': 'ನನ್ನ ಜಮೀನು',
      'today': 'ಇಂದಿನ ವಾತಾವರಣ',
      'spraying_condition': 'ಸಿಂಪಡಣೆ ಸ್ಥಿತಿ',
      'weather_spraying': 'ಹವಾಮಾನ ಮತ್ತು ಸಿಂಪಡಣೆ',
      'farm_tools': 'ಕೃಷಿ ಉಪಕರಣಗಳು',
      'crop_library': 'ಬೆಳೆ ಮಾಹಿತಿ',
      'pest_library': 'ಕೀಟ ಮಾಹಿತಿ',
      'disease_library': 'ರೋಗ ಮಾಹಿತಿ',
      'ai_assistant': 'ಎಐ ಕೃಷಿ ಸಹಾಯಕ',
      'ai_assistant_sub': 'ಸರ್ವಮ್ AI ಚಾಲಿತ ಬಹುಭಾಷಾ ಧ್ವನಿ ಕೃಷಿ ತಜ್ಞ',
      'ask_anything': 'ಯಾವುದೇ ಕೃಷಿ ಪ್ರಶ್ನೆ ಕೇಳಿ ಅಥವಾ ಮೈಕ್ ಒತ್ತಿ...',
      'listening': 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ',
      'speaking': 'ಧ್ವನಿ ಉತ್ತರ ಪ್ಲೇ ಆಗುತ್ತಿದೆ...',
      'type_or_speak': 'ಪ್ರಶ್ನೆ ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮೈಕ್ ಒತ್ತಿ',
      'listen_audio': 'ಧ್ವನಿ ಕೇಳಿ',
      'stop_audio': 'ಧ್ವನಿ ನಿಲ್ಲಿಸಿ',
      'quick_questions': 'ತ್ವರಿತ ಪ್ರಶ್ನೆಗಳು',
      'my_actions': 'ನನ್ನ ಕಾರ್ಯಗಳು',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'add_field': 'ಹೊಸ ಜಮೀನು ಸೇರಿಸಿ',
      'request_scan': 'ಡ್ರೋನ್ ಸ್ಕ್ಯಾನ್ ವಿನಂತಿಸಿ',
      'view_weather': 'ಹವಾಮಾನ ನೋಡಿ',
      'tools': 'ಕ್ಯಾಲ್ಕುಲೇಟರ್‌ಗಳು',
      'ask_ai': 'AI ಕೇಳಿ',
      'view_report': 'ವರದಿ ನೋಡಿ',
      'health_score': 'ಬೆಳೆ ಆರೋಗ್ಯ',
      'soil_moisture': 'ಮಣ್ಣಿನ ತೇವಾಂಶ',
      'temperature': 'ತಾಪಮಾನ',
      'humidity': 'ಆರ್ದ್ರತೆ',
      'active_alerts': 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
      'crop_stage': 'ಬೆಳೆಯ ಹಂತ',
      'last_scan': 'ಕೊನೆಯ ಸ್ಕ್ಯಾನ್',
      'next_scan': 'ಮುಂದಿನ ಸ್ಕ್ಯಾನ್',
      'why': 'ಏಕೆ?',
      'what_should_i_do': 'ನಾನು ಏನು ಮಾಡಬೇಕು?',
      'record_action': 'ಕಾರ್ಯ ದಾಖಲಿಸಿ',
      'view_zone': 'ವಲಯ ನೋಡಿ',
      'before_after': 'ಮೊದಲು → ಕಾರ್ಯ → ನಂತರ',
      'early_warning': 'ಮುನ್ನೆಚ್ಚರಿಕೆ',
      'offline_mode': 'ಆಫ್‌ಲೈನ್ ಮೋಡ್',
      'offline_sync': 'ಡೇಟಾ ಸಿಂಕ್ ಮಾಡಿ',
      'language': 'ಭಾಷೆ',
      'role': 'ಪ್ರಸ್ತುತ ಪಾತ್ರ',
      'irrigation_calc': 'ನೀರಾವರಿ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'fertilizer_calc': 'ಗೊಬ್ಬರ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'pesticide_calc': 'ಕೀಟನಾಶಕ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'seed_calc': 'ಬೀಜ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'cost_calc': 'ವೆಚ್ಚ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'area_calc': 'ವಿಸ್ತೀರ್ಣ ಕ್ಯಾಲ್ಕುಲೇಟರ್',
      'prompt_health': 'ನನ್ನ ಜಮೀನಿನ ಆರೋಗ್ಯ ಏಕೆ ಕಡಿಮೆಯಾಗುತ್ತಿದೆ?',
      'prompt_weather': 'ಇಂದು ಸಿಂಪಡಣೆಗೆ ಹವಾಮಾನ ಸೂಕ್ತವಾಗಿದೆಯೇ?',
      'prompt_zone': 'ವಲಯ 2 ರಲ್ಲಿ ತೇವಾಂಶದ ಸಮಸ್ಯೆ ಏನು?',
      'prompt_blight': 'ಬೆಳೆಯಲ್ಲಿ ರೋಗ ತಡೆಯುವುದು ಹೇಗೆ?',
    },
    'te': {
      'app_title': 'అగ్రివ్యాన్',
      'home': 'హోమ్',
      'fields': 'పొలాలు',
      'scans': 'స్కాన్‌లు',
      'reports': 'నివేదికలు',
      'more': 'మరిన్ని',
      'my_farm': 'నా పొలం',
      'today': 'నేటి వాతావరణం',
      'spraying_condition': 'స్ప్రేయింగ్ పరిస్థితి',
      'weather_spraying': 'వాతావరణం & స్ప్రేయింగ్',
      'farm_tools': 'వ్యవసాయ పరికరాలు',
      'crop_library': 'పంట సమాచారం',
      'pest_library': 'పురుగుల సమాచారం',
      'disease_library': 'వ్యాధి సమాచారం',
      'ai_assistant': 'ఏఐ రైతు సహాయకుడు',
      'ai_assistant_sub': 'సర్వం AI ద్వారా బహుభాషా వాయిస్ వ్యవసాయ నిపుణుడు',
      'ask_anything': 'ఏదైనా వ్యవసాయ ప్రశ్న అడగండి లేదా మైక్ నొక్కండి...',
      'listening': 'వింటోంది... మీ భాషలో మాట్లాడండి',
      'speaking': 'వాయిస్ సమాధానం ప్లే అవుతోంది...',
      'type_or_speak': 'ప్రశ్న టైప్ చేయండి లేదా మాట్లాడటానికి మైక్ నొక్కండి',
      'listen_audio': 'వాయిస్ వినండి',
      'stop_audio': 'వాయిస్ ఆపండి',
      'quick_questions': 'త్వరిత ప్రశ్నలు',
      'my_actions': 'నా పనులు',
      'profile': 'ప్రొఫైల్',
      'settings': 'సెట్టింగ్‌లు',
      'add_field': 'కొత్త పొలం జోడించండి',
      'request_scan': 'డ్రోన్ స్కాన్ అభ్యర్థించండి',
      'view_weather': 'వాతావరణం చూడండి',
      'tools': 'క్యాలిక్యులేటర్లు',
      'ask_ai': 'AI ని అడగండి',
      'view_report': 'నివేదిక చూడండి',
      'health_score': 'పంట ఆరోగ్యం',
      'soil_moisture': 'నేల తేమ',
      'temperature': 'ఉష్ణోగ్రత',
      'humidity': 'తేమ',
      'active_alerts': 'యాక్టివ్ హెచ్చరికలు',
      'crop_stage': 'పంట దశ',
      'last_scan': 'చివరి స్కాన్',
      'next_scan': 'తదుపరి స్కాన్',
      'why': 'ఎందుకు?',
      'what_should_i_do': 'నేను ఏమి చేయాలి?',
      'record_action': 'పనిని నమోదు చేయండి',
      'view_zone': 'జోన్ చూడండి',
      'before_after': 'ముందు → పని → తర్వాత',
      'early_warning': 'ముందస్తు హెచ్చరిక',
      'offline_mode': 'ఆఫ్‌లైన్ మోడ్',
      'offline_sync': 'డేటా సింక్ చేయండి',
      'language': 'భాష',
      'role': 'ప్రస్తుత పాత్ర',
      'irrigation_calc': 'నీటిపారుదల క్యాలిక్యులేటర్',
      'fertilizer_calc': 'ఎరువుల క్యాలిక్యులేటర్',
      'pesticide_calc': 'పురుగుమందుల క్యాలిక్యులేటర్',
      'seed_calc': 'విత్తనాల క్యాలిక్యులేటర్',
      'cost_calc': 'ఖర్చు క్యాలిక్యులేటర్',
      'area_calc': 'వైశాల్యం క్యాలిక్యులేటర్',
      'prompt_health': 'నా పొలం ఆరోగ్యం ఎందుకు తగ్గుతోంది?',
      'prompt_weather': 'ఈరోజు స్ప్రేయింగ్‌కు వాతావరణం అనుకూలంగా ఉందా?',
      'prompt_zone': 'జోన్ 2 లో తేమ సమస్య ఏమిటి?',
      'prompt_blight': 'పంటలలో తెగుళ్ళను ఎలా నివారించాలి?',
    }
  };

  static String translate(String key, String langCode) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'en';
    final val = _localizedValues[lang]?[key];
    if (val != null) return val;
    return _localizedValues['en']?[key] ?? key;
  }
}
