class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'AgriSwarm',
      'home': 'Home',
      'fields': 'Fields',
      'scans': 'Scans',
      'reports': 'Reports',
      'more': 'More',
      'my_farm': 'My Farm',
      'today': 'Today',
      'spraying_condition': 'Spraying Condition',
      'weather_spraying': 'Weather & Spraying',
      'farm_tools': 'Farm Tools',
      'crop_library': 'Crop Library',
      'pest_library': 'Pest Library',
      'disease_library': 'Disease Library',
      'ai_assistant': 'AI Farmer Assistant',
      'my_actions': 'My Actions',
      'profile': 'Profile',
      'settings': 'Settings',
      'add_field': 'Add Field',
      'request_scan': 'Request Drone Scan',
      'view_weather': 'View Weather',
      'tools': 'Tools',
      'ask_ai': 'Ask AI',
      'view_report': 'View Report',
      'health_score': 'Field Health',
      'soil_moisture': 'Soil Moisture',
      'temperature': 'Temperature',
      'humidity': 'Humidity',
      'active_alerts': 'Active Alerts',
      'crop_stage': 'Crop Stage',
      'last_scan': 'Last Scan',
      'next_scan': 'Next Scan',
      'why': 'WHY?',
      'what_should_i_do': 'WHAT SHOULD I DO?',
      'record_action': 'Record Action',
      'view_zone': 'View Zone',
      'before_after': 'Before → Action → After',
      'early_warning': 'Early Warning',
      'offline_mode': 'Offline Mode (Data Cached)',
      'offline_sync': 'Sync Offline Data',
      'language': 'Language',
      'role': 'Current Role',
      'irrigation_calc': 'Irrigation Calculator',
      'fertilizer_calc': 'Fertilizer Calculator',
      'pesticide_calc': 'Pesticide Calculator',
      'seed_calc': 'Seed Calculator',
      'cost_calc': 'Farming Cost Calculator',
      'area_calc': 'Farm Area Calculator',
    },
    'hi': {
      'app_title': 'एग्रीस्वार्म',
      'home': 'मुख्य पृष्ठ',
      'fields': 'खेत',
      'scans': 'स्कैन',
      'reports': 'रिपोर्ट',
      'more': 'अधिक',
      'my_farm': 'मेरा खेत',
      'today': 'आज का मौसम',
      'spraying_condition': 'छिड़काव की स्थिति',
      'weather_spraying': 'मौसम और छिड़काव',
      'farm_tools': 'कृषि उपकरण',
      'crop_library': 'फसल पुस्तकालय',
      'pest_library': 'कीट पुस्तकालय',
      'disease_library': 'रोग पुस्तकालय',
      'ai_assistant': 'एआई किसान सहायक',
      'my_actions': 'मेरे कार्य',
      'profile': 'प्रोफ़ाइल',
      'settings': 'सेटिंग्स',
      'add_field': 'नया खेत जोड़ें',
      'request_scan': 'ड्रोन स्कैन का अनुरोध करें',
      'view_weather': 'मौसम देखें',
      'tools': 'कैलकुलेटर',
      'ask_ai': 'एआई से पूछें',
      'view_report': 'रिपोर्ट देखें',
      'health_score': 'फसल स्वास्थ्य',
      'soil_moisture': 'मृदा नमी',
      'temperature': 'तापमान',
      'humidity': 'आर्द्रता',
      'active_alerts': 'सक्रिय अलर्ट',
      'crop_stage': 'फसल की अवस्था',
      'last_scan': 'पिछला स्कैन',
      'next_scan': 'अगला स्कैन',
      'why': 'क्यों?',
      'what_should_i_do': 'मुझे क्या करना चाहिए?',
      'record_action': 'कार्य दर्ज करें',
      'view_zone': 'ज़ोन देखें',
      'before_after': 'पहले → कार्य → बाद में',
      'early_warning': 'प्रारंभिक चेतावनी',
      'offline_mode': 'ऑफ़लाइन मोड (डेटा सहेजा गया)',
      'offline_sync': 'डेटा सिंक करें',
      'language': 'भाषा',
      'role': 'सक्रिय भूमिका',
      'irrigation_calc': 'सिंचाई कैलकुलेटर',
      'fertilizer_calc': 'उर्वरक कैलकुलेटर',
      'pesticide_calc': 'कीटनाशक कैलकुलेटर',
      'seed_calc': 'बीज कैलकुलेटर',
      'cost_calc': 'लागत कैलकुलेटर',
      'area_calc': 'क्षेत्रफल कैलकुलेटर',
    },
    'mr': {
      'app_title': 'अॅग्रीस्वार्म',
      'home': 'मुख्यपृष्ठ',
      'fields': 'शेती',
      'scans': 'स्कॅन',
      'reports': 'अहवाल',
      'more': 'अधिक',
      'my_farm': 'माझी शेती',
      'today': 'आजचे हवामान',
      'spraying_condition': 'फवारणीची स्थिती',
      'weather_spraying': 'हवामान आणि फवारणी',
      'farm_tools': 'शेती साधने',
      'crop_library': 'पीक माहिती',
      'pest_library': 'कीड माहिती',
      'disease_library': 'रोग माहिती',
      'ai_assistant': 'कृषी AI मदतनीस',
      'my_actions': 'माझ्या कृती',
      'profile': 'प्रोफाईल',
      'settings': 'सेटिंग्ज',
      'add_field': 'नवीन शेत जोडा',
      'request_scan': 'ड्रोन स्कॅन मागणी करा',
      'view_weather': 'हवामान पहा',
      'tools': 'कॅल्क्युलेटर',
      'ask_ai': 'AI ला विचारा',
      'view_report': 'अहवाल पहा',
      'health_score': 'पीक आरोग्य',
      'soil_moisture': 'मातीतील ओलावा',
      'temperature': 'तापमान',
      'humidity': 'हवेतील दमटपणा',
      'active_alerts': 'सक्रिय इशारे',
      'crop_stage': 'पिकाची अवस्था',
      'last_scan': 'शेवटचा स्कॅन',
      'next_scan': 'पुढील स्कॅन',
      'why': 'का?',
      'what_should_i_do': 'मी काय केले पाहिजे?',
      'record_action': 'कृतीची नोंद करा',
      'view_zone': 'झोन पहा',
      'before_after': 'पूर्वी → कृती → नंतर',
      'early_warning': 'पूर्व इशारा',
      'offline_mode': 'ऑफलाईन मोड (माहिती सुरक्षित)',
      'offline_sync': 'ऑफलाईन डेटा सिंक करा',
      'language': 'भाषा',
      'role': 'सक्रिय भूमिका',
      'irrigation_calc': 'सिंचन कॅल्क्युलेटर',
      'fertilizer_calc': 'खत कॅल्क्युलेटर',
      'pesticide_calc': 'कीटकनाशक कॅल्क्युलेटर',
      'seed_calc': 'बियाणे कॅल्क्युलेटर',
      'cost_calc': 'खर्च कॅल्क्युलेटर',
      'area_calc': 'क्षेत्रफळ कॅल्क्युलेटर',
    }
  };

  static String translate(String key, String langCode) {
    final lang = _localizedValues.containsKey(langCode) ? langCode : 'en';
    return _localizedValues[lang]?[key] ?? key;
  }
}
